author: Julie Boe
description: Bites available now!
domain: julieboe.com
google_analytics: G-W5GKHNRHCK
permalink: /:categories/:title
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
remote_theme: jekyll/minima@593a05a
title: Author Julie Boe
url: https://julieboe.com
